import express from "express";
import path from "path";
import fs from "fs";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

const app = express();
const PORT = 3000;

// Ensure uploads and data folders exist
const UPLOADS_DIR = path.join(process.cwd(), "uploads");
const DATA_DIR = path.join(process.cwd(), "data");
if (!fs.existsSync(UPLOADS_DIR)) fs.mkdirSync(UPLOADS_DIR, { recursive: true });
if (!fs.existsSync(DATA_DIR)) fs.mkdirSync(DATA_DIR, { recursive: true });

const CONFIG_FILE = path.join(DATA_DIR, "config.json");
const PURCHASES_FILE = path.join(DATA_DIR, "purchases.json");

// Default Fallback PDFs
const createDefaultPdf = (filePath: string, title: string, subtitle: string) => {
  const pdfContent = `%PDF-1.4
1 0 obj
<< /Type /Catalog /Pages 2 0 R >>
endobj
2 0 obj
<< /Type /Pages /Kids [3 0 R] /Count 1 >>
endobj
3 0 obj
<< /Type /Page /Parent 2 0 R /Resources << /Font << /F1 4 0 R >> >> /MediaBox [0 0 612 792] /Contents 5 0 R >>
endobj
4 0 obj
<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>
endobj
5 0 obj
<< /Length 150 >>
stream
BT
/F1 18 Tf
50 700 Td
(${title}) Tj
0 -30 Td
/F1 12 Tf
(${subtitle}) Tj
0 -25 Td
(Thank you for your purchase of SpeakEase!) Tj
0 -20 Td
(This is a 100% compliant, printable PDF generated by the system.) Tj
0 -20 Td
(Go to the Creator Dashboard in the app footer to replace this file with your own!) Tj
ET
endstream
endobj
xref
0 6
0000000000 65535 f 
0000000009 00000 n 
0000000056 00000 n 
0000000111 00000 n 
0000000238 00000 n 
0000000305 00000 n 
trailer
<< /Size 6 /Root 1 0 R >>
startxref
506
%%EOF`;
  fs.writeFileSync(filePath, pdfContent, "utf-8");
};

// Seed default PDFs if they don't exist
const pdf1Path = path.join(UPLOADS_DIR, "guide-1.pdf");
const pdf2Path = path.join(UPLOADS_DIR, "guide-2.pdf");
if (!fs.existsSync(pdf1Path)) {
  createDefaultPdf(pdf1Path, "SpeakEase: The Clear Speech Guide", "How Indian Professionals Speak with Clarity and Confidence");
}
if (!fs.existsSync(pdf2Path)) {
  createDefaultPdf(pdf2Path, "SpeakEase: The Global Accent Guide", "The Accent neutralization & Metronome speed patterns playbook");
}

// Read/write config (price, etc.)
let activePrice = 399;
if (fs.existsSync(CONFIG_FILE)) {
  try {
    const data = JSON.parse(fs.readFileSync(CONFIG_FILE, "utf-8"));
    if (typeof data.price === "number") activePrice = data.price;
  } catch (err) {
    console.error("Error reading config", err);
  }
}

// Read/write mock purchases
let purchases: any[] = [
  {
    id: "tx_101",
    fullName: "Rohan Sharma",
    email: "rohan@gmail.com",
    amount: 399,
    paymentMethod: "UPI (Google Pay)",
    date: "2026-07-01T14:32:00.000Z"
  },
  {
    id: "tx_102",
    fullName: "Ananya Iyer",
    email: "ananya.iyer@design.io",
    amount: 399,
    paymentMethod: "Visa Card (*4242)",
    date: "2026-07-02T09:15:00.000Z"
  }
];

if (fs.existsSync(PURCHASES_FILE)) {
  try {
    purchases = JSON.parse(fs.readFileSync(PURCHASES_FILE, "utf-8"));
  } catch (err) {
    console.error("Error reading purchases", err);
  }
} else {
  fs.writeFileSync(PURCHASES_FILE, JSON.stringify(purchases, null, 2));
}

// Set high body limit to receive audio base64 and PDF base64 data
app.use(express.json({ limit: "15mb" }));

// Lazy initializer for Gemini Client
let aiClient: GoogleGenAI | null = null;
function getGeminiClient(): GoogleGenAI {
  if (!aiClient) {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error("GEMINI_API_KEY environment variable is required");
    }
    aiClient = new GoogleGenAI({
      apiKey,
      httpOptions: {
        headers: {
          "User-Agent": "aistudio-build",
        },
      },
    });
  }
  return aiClient;
}

// API endpoint for voice evaluation
app.post("/api/evaluate-voice", async (req, res) => {
  try {
    const { audioBase64, mimeType } = req.body;

    if (!audioBase64) {
      return res.status(400).json({ error: "Missing audio data" });
    }

    const hasApiKey = !!process.env.GEMINI_API_KEY;

    if (!hasApiKey) {
      // Return a highly realistic mock response to ensure usability when API Key is missing
      console.warn("GEMINI_API_KEY is not defined. Returning realistic mock evaluation.");
      return res.json({
        isMock: true,
        overallScore: 74,
        clarityScore: 76,
        pacingScore: 68,
        confidenceScore: 78,
        pacingWpm: 154,
        pacingAssessment: "Too Fast",
        primaryChallenge: "Syllable stress and 'v' vs 'w' distinction",
        strengths: [
          "Strong grammatical sentence construction",
          "Excellent natural vocabulary and engagement",
          "Clear vocal projection and pitch"
        ],
        challenges: [
          "Speaking too quickly (154 WPM) under pitch pressure",
          "Merging the 'v' and 'w' sounds (e.g. pronouncing 'very' like 'wery')",
          "Flat intonation at sentence endings instead of descending tone"
        ],
        pronunciationIssues: [
          {
            "word": "Value",
            "observation": "Pronounced with a 'w' sound starter.",
            "correction": "Bite your bottom lip gently with your upper teeth for a clean 'v' sound."
          },
          {
            "word": "Development",
            "observation": "Stressed the first syllable (DE-velopment).",
            "correction": "Stress the second syllable (de-VEL-opment) to match global neutral standards."
          }
        ],
        drillRecommendation: "The 'v' vs 'w' Lip-Teeth Drill (SpeakEase Guide 1, Page 12) & The Metronome Speed Clamp (Guide 2, Page 8)",
        coachingNote: "Your foundational English is excellent, but speaking at 154 WPM makes you sound rushed to Western clients, reducing perceived competence. By pacing down to 130 WPM and correcting syllable stress, you can command 15-20% higher project rates."
      });
    }

    const ai = getGeminiClient();

    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: [
        {
          inlineData: {
            data: audioBase64,
            mimeType: mimeType || "audio/webm",
          },
        },
        {
          text: `You are an expert vocal clarity coach specializing in helping Indian freelancers (Upwork, Fiverr, etc.) improve their speaking clarity, pronunciation, and pacing for US, UK, and Australian clients.

Analyze this voice recording and evaluate their vocal traits for a pitch.

Provide a comprehensive, highly professional, constructive Qoves-style report. Your response MUST be valid JSON matching this schema:
{
  "overallScore": number (1-100),
  "clarityScore": number (1-100),
  "pacingScore": number (1-100),
  "confidenceScore": number (1-100),
  "pacingWpm": number (estimated words per minute),
  "pacingAssessment": "Too Fast" | "Too Slow" | "Perfect Pacing",
  "primaryChallenge": "string (e.g. syllable stress, 'v' vs 'w' pronunciation, flat intonation)",
  "strengths": ["string", "string", "string"],
  "challenges": ["string", "string", "string"],
  "pronunciationIssues": [
    {
      "word": "string",
      "observation": "string",
      "correction": "string"
    }
  ],
  "drillRecommendation": "string (specific action mapping to SpeakEase Guide 01 or Guide 02)",
  "coachingNote": "string (a helpful, warm, encouraging but objective Qoves-style summary paragraph of their performance and potential pitch impact)"
}

Do not add any markdown framing outside the JSON itself.`,
        },
      ],
      config: {
        responseMimeType: "application/json",
      },
    });

    const textOutput = response.text || "{}";
    const cleanedText = textOutput.trim().replace(/^```json\s*/i, "").replace(/```\s*$/, "");
    const parsedData = JSON.parse(cleanedText);
    
    return res.json(parsedData);
  } catch (error: any) {
    console.error("Vocal evaluation endpoint error:", error);
    return res.status(500).json({ error: error?.message || "Internal evaluation error" });
  }
});

// --- CHECKOUT & ADMIN PORTAL API ENDPOINTS ---

// Get active config, uploaded files status, and transaction history
app.get("/api/checkout/config", (req, res) => {
  const hasGuide1 = fs.existsSync(path.join(UPLOADS_DIR, "guide-1.pdf"));
  const hasGuide2 = fs.existsSync(path.join(UPLOADS_DIR, "guide-2.pdf"));
  
  res.json({
    price: activePrice,
    stripePublicKeyPresent: !!process.env.VITE_STRIPE_PUBLIC_KEY || !!process.env.STRIPE_PUBLIC_KEY,
    hasGuide1,
    hasGuide2,
    purchases
  });
});

// Update active price in config
app.post("/api/checkout/save-config", (req, res) => {
  try {
    const { price } = req.body;
    if (typeof price !== "number" || price <= 0) {
      return res.status(400).json({ error: "Invalid price value" });
    }
    
    activePrice = price;
    fs.writeFileSync(CONFIG_FILE, JSON.stringify({ price: activePrice }, null, 2));
    res.json({ success: true, price: activePrice });
  } catch (err: any) {
    res.status(500).json({ error: err?.message || "Failed to save config" });
  }
});

// Record a new purchase transaction (UPI / Card checkout confirmation)
app.post("/api/checkout/record-purchase", (req, res) => {
  try {
    const { fullName, email, amount, paymentMethod } = req.body;
    if (!fullName || !email) {
      return res.status(400).json({ error: "Missing required fields (fullName, email)" });
    }
    
    const newPurchase = {
      id: "tx_" + Date.now(),
      fullName,
      email,
      amount: amount || activePrice,
      paymentMethod: paymentMethod || "Simulated UPI/Card",
      date: new Date().toISOString()
    };
    
    purchases.unshift(newPurchase); // Add to beginning
    fs.writeFileSync(PURCHASES_FILE, JSON.stringify(purchases, null, 2));
    
    res.json({ success: true, purchase: newPurchase });
  } catch (err: any) {
    res.status(500).json({ error: err?.message || "Failed to record purchase" });
  }
});

// Upload a new PDF file replacing standard guide
app.post("/api/admin/upload-pdf", (req, res) => {
  try {
    const { guideId, fileName, fileBase64 } = req.body;
    if (!guideId || !fileBase64) {
      return res.status(400).json({ error: "Missing required fields (guideId, fileBase64)" });
    }
    
    if (guideId !== "guide-1" && guideId !== "guide-2") {
      return res.status(400).json({ error: "Invalid guideId. Must be 'guide-1' or 'guide-2'." });
    }
    
    // Decode base64 to binary buffer
    const buffer = Buffer.from(fileBase64, "base64");
    const targetPath = path.join(UPLOADS_DIR, `${guideId}.pdf`);
    
    fs.writeFileSync(targetPath, buffer);
    console.log(`Successfully uploaded ${fileName} to ${targetPath}`);
    
    res.json({ success: true, fileName });
  } catch (err: any) {
    console.error("PDF upload error", err);
    res.status(500).json({ error: err?.message || "Failed to upload PDF file" });
  }
});

// Download secure PDF
app.get("/api/download-pdf", (req, res) => {
  try {
    const { guideId } = req.query;
    if (guideId !== "guide-1" && guideId !== "guide-2") {
      return res.status(400).send("Invalid guide identifier");
    }
    
    const targetPath = path.join(UPLOADS_DIR, `${guideId}.pdf`);
    if (!fs.existsSync(targetPath)) {
      return res.status(404).send("PDF guide file not found. Contact administrator.");
    }
    
    const fileName = guideId === "guide-1" ? "The_Clear_Speech_Guide.pdf" : "The_Global_Accent_Guide_Bonus.pdf";
    
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="${fileName}"`);
    
    const fileStream = fs.createReadStream(targetPath);
    fileStream.pipe(res);
  } catch (err: any) {
    console.error("PDF download error", err);
    res.status(500).send("Failed to stream PDF file");
  }
});

// Configure Vite or Static Assets based on environment
async function setupServer() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://0.0.0.0:${PORT}`);
  });
}

setupServer();
